.Dd October 24, 2016
.Dt JOULU 1
.Os Niksula
.Sh NAME
.Nm joulu
.Nd Niksula's joulu
.Sh SYNOPSIS
.Nm joulu
.Sh DESCRIPTION
.Nm
displays something nice every day during December before the 25th day.
.Pp
.Em The Niksula Gurus wish you a Merry Christmas and a Happy New Year!
.Pp
.Sy -- The feared Urug of Niksula
.Sh ENVIRONMENT
.Nm
will utilize the following environment variables if they exist:
.Bl -tag -width Ds
.It Ev HOME
The place where you should be when it's holiday. Not in Paniikki doing some
coding :)
.El
.Sh SEE ALSO
.Lk https://www.niksula.hut.fi/
