.TH JOULU 1 "2004 December 1" TiK
.SH NAME
joulu \- Niksula's joulu
.SH SYNOPSIS
\fBjoulu\fP
.SH DESCRIPTION
.B joulu
is a shell script to display something nice every day during
December before the 25th day.
.TP
\fIThe Niksula Gurus wish you Merry Christmas and Happy New Year!\fP
.TP
.B -- The feared Urug of Niksula
.SH ENVIRONMENT
.B joulu
will utilize the following environment variables if they exist:
.TP
.B HOME
The place where you should be when it's holiday. Not in Paniikki doing some coding :)
.SH SEE ALSO
.B http://www.niksula.hut.fi/
