$CPAN::Config = {
  'applypatch' => q[],
  'auto_commit' => q[0],
  'build_cache' => q[100],
  'build_dir' => q[@TMPDIR@/cpan/build],
  'build_dir_reuse' => q[0],
  'build_requires_install_policy' => q[yes],
  'bzip2' => q[/usr/bin/bzip2],
  'cache_metadata' => q[1],
  'check_sigs' => q[1],
  'colorize_output' => q[0],
  'commandnumber_in_prompt' => q[1],
  'connect_to_internet_ok' => q[1],
  'cpan_home' => q[@TMPDIR@/cpan],
  'ftp_passive' => q[1],
  'ftp_proxy' => q[],
  'getcwd' => q[cwd],
  'gpg' => q[/opt/niksula/bin/gpg],
  'gzip' => q[/usr/bin/gzip],
  'halt_on_failure' => q[1],
  'histfile' => q[@TMPDIR@/cpan/histfile],
  'histsize' => q[0],
  'http_proxy' => q[],
  'inactivity_timeout' => q[0],
  'index_expire' => q[1],
  'inhibit_startup_message' => q[0],
  'keep_source_where' => q[@TMPDIR@/cpan/sources],
  'load_module_verbosity' => q[none],
  'make' => q[/usr/bin/gmake],
  # some CPAN modules generate makefiles which set MAKE=make
  'make_arg' => q[@MAKE_JOBS@ MAKE=gmake],
  'make_install_arg' => q[@MAKE_JOBS@ MAKE=gmake],
  'make_install_make_command' => q[/usr/bin/gmake],
  'makepl_arg' => q[DESTDIR=@DESTDIR@/ INSTALL_BASE=@PREFIX@],
  'mbuild_arg' => q[],
  'mbuild_install_arg' => q[],
  'mbuild_install_build_command' => q[./Build],
  'mbuildpl_arg' => q[--destdir @DESTDIR@/ --install_base=@PREFIX@],
  'no_proxy' => q[],
  'pager' => q[less],
  'patch' => q[/usr/bin/patch],
  'perl5lib_verbosity' => q[v],
  'prefer_external_tar' => q[0],
  'prefer_installer' => q[MB],
  'prefs_dir' => q[@TMPDIR@/cpan/prefs],
  'prerequisites_policy' => q[follow],
  'scan_cache' => q[atstart],
  'shell' => q[/bin/zsh],
  'show_unparsable_versions' => q[0],
  'show_upload_date' => q[0],
  'show_zero_versions' => q[0],
  'tar' => q[/usr/bin/gtar],
  'tar_verbosity' => q[none],
  'term_is_latin' => q[0],
  'term_ornaments' => q[1],
  'test_report' => q[0],
  'trust_test_report_history' => q[0],
  'unzip' => q[/usr/bin/unzip],
  'urllist' => [q[ftp://ftp.funet.fi/pub/languages/perl/CPAN/]],
  'use_sqlite' => q[0],
  'version_timeout' => q[15],
  'wget' => q[/usr/bin/wget],
  'yaml_load_code' => q[0],
  'yaml_module' => q[YAML],
};
1;
__END__
